version: '3.9'

services:
  db:
    image: postgres:15
    volumes:
      - ./database/postgres_data:/var/lib/postgresql/data
    environment:
       POSTGRES_HOST: ${DB_HOST}
       POSTGRES_USER: ${DB_USER}
       POSTGRES_PASSWORD: ${DB_PASSWORD}
       POSTGRES_DB: ${DB_NAME}

    restart: on-failure

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${USER} -d ${NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  front:
    image: sermalenk/skypro-front:lesson-34
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy

  migrations:
    image: trevor5f/todolist_project:${GITHUB_REF_NAME}-${GITHUB_RUN_IDbuild}
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "python manage.py migrate"   

  api:
    image: trevor5f/todolist_project:${GITHUB_REF_NAME}-${GITHUB_RUN_IDbuild}


    depends_on:
      db:
        condition: service_healthy


volumes:
  postgres_data:

